services:    
    vlei-server:
        image: gleif/vlei:0.2.0
        environment:
            - PYTHONUNBUFFERED=1
            - PYTHONIOENCODING=UTF-8
        command:
            - vLEI-server
            - -s
            - ./schema/acdc
            - -c
            - ./samples/acdc/
            - -o
            - ./samples/oobis/
        ports:
            - 7723:7723
        network_mode: host

    witness-demo:
        image: weboftrust/keri:1.1.22
        environment:
            - PYTHONUNBUFFERED=1
            - PYTHONIOENCODING=UTF-8
        entrypoint: kli
        command:
            - witness
            - demo
        volumes:
            - ./config/witness-demo:/keripy/scripts/keri/cf/main
        ports:
            - 5642:5642
            - 5643:5643
            - 5644:5644
            - 5645:5645
            - 5646:5646
            - 5647:5647
        network_mode: host

    manager:
        image: sally-image
        environment:
            - PYTHONUNBUFFERED=1
            - PYTHONIOENCODING=UTF-8
        entrypoint: sally
        command:
            - hook
            - demo
        ports:
            - 9923:9923
        network_mode: host

    vlei-reporting:
        image: sally-image
        environment:
            - PYTHONUNBUFFERED=1
            - PYTHONIOENCODING=UTF-8
        volumes:
            - ./config/sally-oobis.json:/sally/scripts/keri/cf/sally-oobis.json
            - ./config/sally-incept.json:/sally/sally-incept.json
        depends_on:
            - vlei-server           
            - witness-demo
        entrypoint: ["/bin/bash", "-c"]
        command: |
            "sleep 10 &&
            kli init --name sally --nopasscode --config-dir /sally/scripts --config-file sally-oobis --salt 0ACDXyMzq1Nxc4OWxtbm9fle &&
            kli incept --name sally --alias sally --file /sally/sally-incept.json &&
            sally server start --name sally --alias sally --web-hook http://47.129.32.41:9923 --auth EHOuGiHMxJShXHgSb6k_9pqxmRb8H-LT0R2hQouHp8pW
            "
        ports:
            - 9723:9723
        network_mode: host