version: '3.8'
services:
    express-server:
        build:
            context: ./
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/usr/src/app:delegated
        ports:
            - 3000:3000
        command: npm start
